# **Tensor Basics - Patrick Loeber**

Importing torch

In [1]:
import torch

Printing empty tensor

In [2]:
x=torch.empty(1) #Size is 1
print(x)

tensor([0.])


Printing empty tensor with size (3)

In [3]:
x=torch.empty(3) #Size is 3
print(x) #The Garbage Values [3.8877e-33,  4.3299e-41, -5.8776e-27] indicate that the values in the tensor are not initialized

tensor([0., 0., 0.])


Printing empty tensor with size (2,3)

In [4]:
x=torch.empty(2,3) #2D Vector
print(x)

tensor([[3.2049e-30, 1.1953e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Printing empty tensor with size (2,2,3)

In [6]:
x=torch.empty(2,2,3) #3D Vector
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


Random Values in Tensor

In [7]:
x=torch.rand(2,2) #The values intialized in the Tensor are Randomized
print(x)

tensor([[0.7645, 0.5582],
        [0.4339, 0.8254]])


All values in Tensor are Zero

In [8]:
x=torch.zeros(2,2) #All the values initalized in the Tensor are Zero
print(x)

tensor([[0., 0.],
        [0., 0.]])


All values in Tensor are One

In [9]:
x=torch.ones(2,2) #All the values initalized in the Tensor are One
print(x)

tensor([[1., 1.],
        [1., 1.]])


Checking the datatype used by Tensor

In [10]:
x=torch.ones(2,2)
print(x.dtype)

torch.float32


Initializing the datatype to be used by Tensor

In [11]:
x=torch.ones(1,1,dtype=torch.int)
print(x.dtype)

torch.int32


In [12]:
x=torch.ones(1,1,dtype=torch.float16)
print(x.dtype)

torch.float16


Checking the size of a tensor

In [13]:
x=torch.ones(2,2)
print(x.size())

torch.Size([2, 2])


Initializing Tensor with Values

In [14]:
x=torch.tensor([2.5,0.1])
print(x)
print(x.size())
print(x.dtype)

tensor([2.5000, 0.1000])
torch.Size([2])
torch.float32


Adding two Tensors

In [16]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print('X = ',x)
print('Y = ',y)
w = x+y #Both the function and normal addition would perform the same action
z=torch.add(x,y)
print('W = ',w)
print('Z = ',z)

X =  tensor([[0.5623, 0.3964],
        [0.9499, 0.6885]])
Y =  tensor([[0.3318, 0.6896],
        [0.2617, 0.9293]])
W =  tensor([[0.8942, 1.0859],
        [1.2116, 1.6178]])
Z =  tensor([[0.8942, 1.0859],
        [1.2116, 1.6178]])


Inline Addition

In [17]:
x=torch.rand(2,2)
y=torch.rand(2,2)
y.add_(x) #In PyTorch, every function that has a trailing underscore, will do an inplace operation, so this modify the variable that it is applied on.
print(y)

tensor([[0.6927, 0.1526],
        [0.9572, 1.4946]])


Subtraction between two Tensors

In [18]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print('X = ',x)
print('Y = ',y)
w = x-y #Both the function and normal subtraction would perform the same action
z=torch.sub(x,y)
print('W = ',w)
print('Z = ',z)

X =  tensor([[0.8761, 0.2499],
        [0.6651, 0.5706]])
Y =  tensor([[0.6675, 0.6374],
        [0.2322, 0.3076]])
W =  tensor([[ 0.2085, -0.3874],
        [ 0.4329,  0.2630]])
Z =  tensor([[ 0.2085, -0.3874],
        [ 0.4329,  0.2630]])


Multiplication between two Tensors

In [19]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print('X = ',x)
print('Y = ',y)
w = x*y #Both the function and normal mutiplication would perform the same action
z=torch.mul(x,y)
print('W = ',w)
print('Z = ',z)

X =  tensor([[0.9292, 0.6600],
        [0.8788, 0.2529]])
Y =  tensor([[0.7099, 0.0764],
        [0.3451, 0.5080]])
W =  tensor([[0.6596, 0.0504],
        [0.3032, 0.1285]])
Z =  tensor([[0.6596, 0.0504],
        [0.3032, 0.1285]])


Division between two Tensors

In [20]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print('X = ',x)
print('Y = ',y)
w = x/y #Both the function and normal division would perform the same action
z=torch.div(x,y)
print('W = ',w)
print('Z = ',z)

X =  tensor([[0.4458, 0.4692],
        [0.1529, 0.9606]])
Y =  tensor([[0.5491, 0.6020],
        [0.8268, 0.7643]])
W =  tensor([[0.8118, 0.7793],
        [0.1850, 1.2568]])
Z =  tensor([[0.8118, 0.7793],
        [0.1850, 1.2568]])


Slicing Operation

In [21]:
x=torch.rand(5,3)
print('X = ',x)
print('\n','First column but all the rows =',x[:,0])
print('\n','First row but all the columns = ',x[0,:])
print('\n','Element at position [2,2] = ',x[2,2])
print('\n','Actual Value at position [2,2] = ',x[2,2].item()) #Item function can only be used if we have one element

X =  tensor([[0.5516, 0.7369, 0.2873],
        [0.1280, 0.2162, 0.4320],
        [0.4588, 0.4802, 0.8661],
        [0.0431, 0.5528, 0.4727],
        [0.4522, 0.1092, 0.1005]])

 First column but all the rows = tensor([0.5516, 0.1280, 0.4588, 0.0431, 0.4522])

 First row but all the columns =  tensor([0.5516, 0.7369, 0.2873])

 Element at position [2,2] =  tensor(0.8661)

 Actual Value at position [2,2] =  0.866091787815094


Reshaping a Tensor

In [22]:
x=torch.rand(4,4) # 4x4
print(x)
y=x.view(16) # 16 (The no. of elements must remain the same)
print(y)
z=x.view(-1, 8) # Using -1 will cause PyTorch to automatically detect the number of rows (or cols) that are necessary (which is 2 in this case)
print(z)

tensor([[0.4272, 0.6778, 0.1179, 0.1375],
        [0.3437, 0.8250, 0.8385, 0.5482],
        [0.2544, 0.1341, 0.4080, 0.7286],
        [0.2790, 0.8377, 0.4167, 0.5629]])
tensor([0.4272, 0.6778, 0.1179, 0.1375, 0.3437, 0.8250, 0.8385, 0.5482, 0.2544,
        0.1341, 0.4080, 0.7286, 0.2790, 0.8377, 0.4167, 0.5629])
tensor([[0.4272, 0.6778, 0.1179, 0.1375, 0.3437, 0.8250, 0.8385, 0.5482],
        [0.2544, 0.1341, 0.4080, 0.7286, 0.2790, 0.8377, 0.4167, 0.5629]])


Converting from Torch Tensor to NumPy ndarray

In [23]:
#Importing NumPy
import numpy as np

In [24]:
x=torch.ones(5)
print('Torch = ',x)
y=x.numpy()
print('NumPy Array = ',y)
print(y)
print('Y type = ', type(y))

Torch =  tensor([1., 1., 1., 1., 1.])
NumPy Array =  [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
Y type =  <class 'numpy.ndarray'>


Both the Ndarray and the Tensor both point to the same memory location

In [25]:
x=torch.ones(5)
print('Torch = ',x)
y=x.numpy()
print('NumPy Array = ',y)
x.add_(1)
print('After Addition: ')
print('Torch = ',x)
print('NumPy Array = ',y)

Torch =  tensor([1., 1., 1., 1., 1.])
NumPy Array =  [1. 1. 1. 1. 1.]
After Addition: 
Torch =  tensor([2., 2., 2., 2., 2.])
NumPy Array =  [2. 2. 2. 2. 2.]


NumPy Array to Tensor

In [26]:
x=np.ones(5)
print('NumPy Array = ',x)
y=torch.from_numpy(x)
print('Torch = ',y)
x+=1
print('After Addition: ')
print('Torch = ',x)
print('NumPy Array = ',y) #This only happens if the tensor is on the CPU

NumPy Array =  [1. 1. 1. 1. 1.]
Torch =  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
After Addition: 
Torch =  [2. 2. 2. 2. 2.]
NumPy Array =  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Checking if CUDA is available

In [27]:
if torch.cuda.is_available():
  print('True')
else:
  print('False')

True


Shifting/Initializing Tensor to GPU

In [29]:
device=torch.device("cuda")
x = torch.ones(5, device=device)
y = torch.ones(5)
y = y.to(device)
z = x + y
#z.numpy() # Will give error as you cant convert a GPU tensor back to NumPy
z = z.to("cpu") # Tensor will be back to CPU again
z.numpy() # Will work

array([2., 2., 2., 2., 2.], dtype=float32)

Tells PyTorch that it will need to calculate the gradients for the Tensor later in Optimization steps (When a variable needs Optimization)

In [30]:
x=torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
