# **Tensor Basics - Patrick Loeber**

Importing torch

In [1]:
import torch

Printing empty tensor

In [ ]:
x=torch.empty(1) #Size is 1
print(x)

tensor([0.])


Printing empty tensor with size (3)

In [ ]:
x=torch.empty(3) #Size is 3
print(x) #The Garbage Values [3.8877e-33,  4.3299e-41, -5.8776e-27] indicate that the values in the tensor are not initialized

tensor([ 3.8877e-33,  4.3299e-41, -5.8776e-27])


Printing empty tensor with size (2,3)

In [ ]:
x=torch.empty(2,3) #2D Vector
print(x)

tensor([[-7.8999e-27,  3.2268e-41, -8.0566e-27],
        [ 3.2268e-41,  1.9540e-33,  4.3299e-41]])


Printing empty tensor with size (2,2,3)

In [ ]:
x=torch.empty(2,2,3) #3D Vector
print(x)

tensor([[[ 0.0000e+00,  0.0000e+00, -5.8778e-27],
         [ 3.2268e-41, -1.1302e-27,  3.2268e-41]],

        [[ 1.3769e-24,  4.3297e-41,  1.4013e-45],
         [ 0.0000e+00,  8.4078e-45,  0.0000e+00]]])


Random Values in Tensor

In [ ]:
x=torch.rand(2,2) #The values intialized in the Tensor are Randomized
print(x)

tensor([[0.4796, 0.7553],
        [0.9538, 0.8422]])


All values in Tensor are Zero

In [ ]:
x=torch.zeros(2,2) #All the values initalized in the Tensor are Zero
print(x)

tensor([[0., 0.],
        [0., 0.]])


All values in Tensor are One

In [ ]:
x=torch.ones(2,2) #All the values initalized in the Tensor are One
print(x)

tensor([[1., 1.],
        [1., 1.]])


Checking the datatype used by Tensor

In [ ]:
x=torch.ones(2,2)
print(x.dtype)

torch.float32


Initializing the datatype to be used by Tensor

In [ ]:
x=torch.ones(1,1,dtype=torch.int)
print(x.dtype)

torch.int32


In [ ]:
x=torch.ones(1,1,dtype=torch.float16)
print(x.dtype)

torch.float16


Checking the size of a tensor

In [ ]:
x=torch.ones(2,2)
print(x.size())

torch.Size([2, 2])


Initializing Tensor with Values

In [ ]:
x=torch.tensor([2.5,0.1])
print(x)
print(x.size())
print(x.dtype)

tensor([2.5000, 0.1000])
torch.Size([2])
torch.float32


Adding two Tensors

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print('X = ',x)
print('Y = ',y)
w = x+y #Both the function and normal addition would perform the same action
z=torch.add(x,y)
print('W = ',w)
print('Z = ',z)

X =  tensor([[0.1651, 0.6446],
        [0.4482, 0.1896]])
Y =  tensor([[0.6428, 0.0550],
        [0.5726, 0.4584]])
W =  tensor([[0.8079, 0.6995],
        [1.0208, 0.6480]])
Z =  tensor([[0.8079, 0.6995],
        [1.0208, 0.6480]])


Inline Addition

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
y.add_(x) #In PyTorch, every function that has a trailing underscore, will do an inplace operation, so this modify the variable that it is applied on.
print(y)

Subtraction between two Tensors

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print('X = ',x)
print('Y = ',y)
w = x-y #Both the function and normal subtraction would perform the same action
z=torch.sub(x,y)
print('W = ',w)
print('Z = ',z)

X =  tensor([[0.8941, 0.8697],
        [0.4215, 0.8450]])
Y =  tensor([[0.6848, 0.6828],
        [0.5594, 0.6638]])
W =  tensor([[ 0.2092,  0.1870],
        [-0.1379,  0.1811]])
Z =  tensor([[ 0.2092,  0.1870],
        [-0.1379,  0.1811]])


Multiplication between two Tensors

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print('X = ',x)
print('Y = ',y)
w = x*y #Both the function and normal mutiplication would perform the same action
z=torch.mul(x,y)
print('W = ',w)
print('Z = ',z)

X =  tensor([[0.0011, 0.0098],
        [0.7291, 0.3177]])
Y =  tensor([[0.2120, 0.9313],
        [0.4382, 0.3805]])
W =  tensor([[2.3369e-04, 9.1611e-03],
        [3.1952e-01, 1.2088e-01]])
Z =  tensor([[2.3369e-04, 9.1611e-03],
        [3.1952e-01, 1.2088e-01]])


Division between two Tensors

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print('X = ',x)
print('Y = ',y)
w = x/y #Both the function and normal division would perform the same action
z=torch.div(x,y)
print('W = ',w)
print('Z = ',z)

X =  tensor([[0.9655, 0.0313],
        [0.9090, 0.1272]])
Y =  tensor([[0.5466, 0.2458],
        [0.2764, 0.2043]])
W =  tensor([[1.7664, 0.1275],
        [3.2884, 0.6225]])
Z =  tensor([[1.7664, 0.1275],
        [3.2884, 0.6225]])


Slicing Operation

In [ ]:
x=torch.rand(5,3)
print('X = ',x)
print('\n','First column but all the rows =',x[:,0])
print('\n','First row but all the columns = ',x[0,:])
print('\n','Element at position [2,2] = ',x[2,2])
print('\n','Actual Value at position [2,2] = ',x[2,2].item()) #Item function can only be used if we have one element

X =  tensor([[0.8932, 0.4202, 0.0333],
        [0.1977, 0.4520, 0.8605],
        [0.5320, 0.8825, 0.3459],
        [0.3275, 0.2141, 0.5736],
        [0.2555, 0.0528, 0.4362]])

 First column but all the rows = tensor([0.8932, 0.1977, 0.5320, 0.3275, 0.2555])

 First row but all the columns =  tensor([0.8932, 0.4202, 0.0333])

 Element at position [2,2] =  tensor(0.3459)

 Actual Element at position [2,2] =  0.34587931632995605


Reshaping a Tensor

In [ ]:
x=torch.rand(4,4) # 4x4
print(x)
y=x.view(16) # 16 (The no. of elements must remain the same)
print(y)
z=x.view(-1, 8) # Using -1 will cause PyTorch to automatically detect the number of rows (or cols) that are necessary (which is 2 in this case)
print(z)

tensor([[0.3990, 0.2560, 0.1742, 0.6463],
        [0.7546, 0.7894, 0.6502, 0.0173],
        [0.2612, 0.8166, 0.8616, 0.2496],
        [0.1979, 0.0141, 0.6136, 0.5746]])
tensor([0.3990, 0.2560, 0.1742, 0.6463, 0.7546, 0.7894, 0.6502, 0.0173, 0.2612,
        0.8166, 0.8616, 0.2496, 0.1979, 0.0141, 0.6136, 0.5746])
tensor([[0.3990, 0.2560, 0.1742, 0.6463, 0.7546, 0.7894, 0.6502, 0.0173],
        [0.2612, 0.8166, 0.8616, 0.2496, 0.1979, 0.0141, 0.6136, 0.5746]])


Converting from Torch Tensor to NumPy ndarray

In [2]:
#Importing NumPy
import numpy as np

In [ ]:
x=torch.ones(5)
print('Torch = ',x)
y=x.numpy()
print('NumPy Array = ',y)
print(y)
print('Y type = ', type(y))

Torch =  tensor([1., 1., 1., 1., 1.])
NumPy Array =  [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
Y type =  <class 'numpy.ndarray'>


Both the Ndarray and the Tensor both point to the same memory location

In [6]:
x=torch.ones(5)
print('Torch = ',x)
y=x.numpy()
print('NumPy Array = ',y)
x.add_(1)
print('After Addition: ')
print('Torch = ',x)
print('NumPy Array = ',y)

Torch =  tensor([1., 1., 1., 1., 1.])
NumPy Array =  [1. 1. 1. 1. 1.]
After Addition: 
Torch =  tensor([2., 2., 2., 2., 2.])
NumPy Array =  [2. 2. 2. 2. 2.]


NumPy Array to Tensor

In [10]:
x=np.ones(5)
print('NumPy Array = ',x)
y=torch.from_numpy(x)
print('Torch = ',y)
x+=1
print('After Addition: ')
print('Torch = ',x)
print('NumPy Array = ',y) #This only happens if the tensor is on the CPU

NumPy Array =  [1. 1. 1. 1. 1.]
Torch =  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
After Addition: 
Torch =  [2. 2. 2. 2. 2.]
NumPy Array =  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Checking if CUDA is available

In [12]:
if torch.cuda.is_available():
  print('True')
else:
  print('False')

False


Shifting/Initializing Tensor to GPU

In [ ]:
device=torch.device("cuda")
x = torch.ones(5, device=device)
y = torch.ones(5)
y = y.to(device)
z = x + y
z.numpy() # Will give error as you cant convert a GPU tensor back to NumPy
z = z.to("cpu") # Tensor will be back to CPU again
z.numpy() # Will work

Tells PyTorch that it will need to calculate the gradients for the Tensor later in Optimization steps (When a variable needs Optimization)

In [15]:
x=torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
